CREATE PROC [dbo].[SP_CheckStudentExist]
@MASV char(8)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = @MASV)
		SELECT '1';
	ELSE IF EXISTS (SELECT 1 FROM LINK2.TN_CSDLPT.DBO.SINHVIEN S WHERE S.MASV = @MASV)
		SELECT '1';
	ELSE
		SELECT '0';
END