CREATE PROC [dbo].[SP_CheckQuestionEnough]
@MAMH CHAR(5), @TRINHDO CHAR(1), @SOCAUHOI int
AS
BEGIN

	DECLARE @TRINHDO1 CHAR(1) = 'K'
	DECLARE @SOCAU int = 0
	DECLARE @SC int = 0
	DECLARE @SK int = 0

	IF ( @TRINHDO = 'A' )
		SET @TRINHDO1 = 'B'
	ELSE IF ( @TRINHDO = 'B' )
		SET @TRINHDO1 = 'C'

	SET @SC = ( SELECT COUNT(*) FROM BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO )
	SET @SK = ( SELECT COUNT(*) FROM BODE WHERE MAMH = @MAMH AND TRINHDO = @TRINHDO1 )

	SET @SOCAU = @SC + @SK

	IF ( @SOCAU <@SOCAUHOI OR @SC < ( @SOCAUHOI * 70 / 100 ) )
		SELECT '0';
	ELSE
		SELECT '1';	
	
END