ALTER PROC SP_GetReport
@MACS nchar(3), @FROM datetime, @TO datetime
AS
BEGIN
	

	IF EXISTS (SELECT 1 FROM COSO WHERE MACS = @MACS)
		BEGIN

			SELECT MALOP, MAMH, MAGV, LAN, SOCAUTHI, NGAYTHI INTO #TEMP1 FROM GIAOVIEN_DANGKY WHERE NGAYTHI BETWEEN @FROM AND @TO

			SELECT K.MALOP, K.MAMH, K.LAN, COUNT(B.BAITHI) AS 'DATHI'  INTO #TEMP2
			FROM 
			(SELECT T.MALOP, T.MAMH, T.LAN, S.MASV FROM #TEMP1 T LEFT JOIN SINHVIEN S ON T.MALOP = S.MALOP) AS K 
			LEFT JOIN 
			(SELECT MASV, MAMH, LAN, BAITHI FROM BANGDIEM) AS B
			ON
			K.MASV =B.MASV AND K.MAMH = B.MAMH AND K.LAN = B.LAN
			GROUP BY K.MALOP, K.MAMH, K.LAN

			SELECT L.TENLOP, M.TENMH, (G.HO + G.TEN) AS HOTEN, T1.LAN, T1.SOCAUTHI, T1.NGAYTHI, T2.DATHI
			FROM #TEMP1 T1, #TEMP2 T2, (SELECT MAGV, HO, TEN FROM GIAOVIEN) AS G, MONHOC M, LOP L
			WHERE T1.MALOP = T2.MALOP AND T1.MAMH = T2.MAMH AND T1.LAN = T2.LAN AND T1.MAGV = G.MAGV AND T1.MAMH = M.MAMH AND T1.MALOP = L.MALOP

			DROP TABLE #TEMP1
			DROP TABLE #TEMP2

		END

	ELSE

		BEGIN

			SELECT MALOP, MAMH, MAGV, LAN, SOCAUTHI, NGAYTHI INTO #TEMP3 FROM LINK1.TN_CSDLPT.DBO.GIAOVIEN_DANGKY WHERE NGAYTHI BETWEEN @FROM AND @TO

			SELECT K.MALOP, K.MAMH, K.LAN, COUNT(B.BAITHI) AS 'DATHI'  INTO #TEMP4
			FROM 
			(SELECT T.MALOP, T.MAMH, T.LAN, S.MASV FROM #TEMP3 T LEFT JOIN LINK1.TN_CSDLPT.DBO.SINHVIEN S ON T.MALOP = S.MALOP) AS K 
			LEFT JOIN 
			(SELECT MASV, MAMH, LAN, BAITHI FROM LINK1.TN_CSDLPT.DBO.BANGDIEM) AS B
			ON
			K.MASV =B.MASV AND K.MAMH = B.MAMH AND K.LAN = B.LAN
			GROUP BY K.MALOP, K.MAMH, K.LAN

			SELECT L.TENLOP, M.TENMH, (G.HO + G.TEN) AS HOTEN, T1.LAN, T1.SOCAUTHI, T1.NGAYTHI, T2.DATHI
			FROM #TEMP3 T1, #TEMP4 T2, (SELECT MAGV, HO, TEN FROM LINK1.TN_CSDLPT.DBO.GIAOVIEN) AS G, MONHOC M, LINK1.TN_CSDLPT.DBO.LOP L
			WHERE T1.MALOP = T2.MALOP AND T1.MAMH = T2.MAMH AND T1.LAN = T2.LAN AND T1.MAGV = G.MAGV AND T1.MAMH = M.MAMH AND T1.MALOP = L.MALOP

			DROP TABLE #TEMP3
			DROP TABLE #TEMP4

		END 
		
END