CREATE PROC SP_InfoExam
@MAMH CHAR(5), @MALOP CHAR(8), @LAN INT, @NGAYTHI DATETIME
AS
BEGIN
	SELECT TRINHDO, SOCAUTHI, THOIGIAN FROM GIAOVIEN_DANGKY WHERE MAMH = @MAMH AND MALOP = @MALOP AND LAN = @LAN AND NGAYTHI = @NGAYTHI
END